[package]
name = "ouisync-ffi"
description = "Secure P2P file sharing (foreign function interface)"
version = "0.1.0"
authors = ["Adam Cig√°nek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
license = "MPL-2.0"
repository = "https://github.com/equalitie/ouisync"
edition = "2021"
rust-version = "1.56.0"
publish = false

[lib]
crate-type = ["cdylib"] # TODO: we might also need `staticlib` for ios

[dependencies]
camino = "1.0.9"
env_logger = "0.9.0"
hex = "0.4.3"
tracing = { version = "0.1.35", features = ["log"] }
ouisync-lib = { package = "ouisync", version = "0.2", path = "../lib" }
rmp-serde = "1.1.0"
tokio = "1.19.2"

[target.'cfg(target_os = "android")'.dependencies]
android_log-sys = "0.2.0"
android_logger = "0.10.1"
libc = "0.2.126"
once_cell = "1.9.0"
os_pipe = "0.9.2"
