[package]
name = "ouisync-cli"
description = "Secure P2P file sharing (command-line interface)"
version = "0.1.0"
authors = ["Adam Cig√°nek <adam@equalit.ie>", "Peter Jankuliak <peter@equalit.ie>"]
license = "MPL-2.0"
edition = "2021"
publish = false
default-run = "ouisync"

[[bin]]
name = "ouisync"
path = "src/main.rs"

[dependencies]
ouisync-lib = { package = "ouisync", version = "0.2", path = "../lib" }
anyhow = "1.0.40"
camino = "1.0.5"
clap = { version = "3.2.2", features = ["derive"] }
dirs = "4.0.0"
env_logger = "0.9.0"
log = "0.4.14"
slab = "0.4.5"
tokio = { version = "1.19.1", features = ["signal"] }
rand = "0.8.4"

[target.'cfg(any(target_os = "linux", target_os = "osx"))'.dependencies]
fuser = "0.11.0"
libc = "0.2.93"

[dev-dependencies]
backoff = "0.4.0"
hex = "0.4.3"
proptest = "1.0"
tempfile = "3.2"
test-strategy = "0.1.1"

