name: ouisync_plugin
description: A flutter plugin providing high-level dart API for the ouisync native library
version: 0.1.0
homepage: null

environment:
  sdk: ^3.1.3
  flutter: ^3.13.6

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  ffi: ^2.0.1
  hex: ^0.2.0
  path: ^1.8.0
  msgpack_dart: ^1.0.1
  platform: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.22.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: ie.equalit.ouisync_plugin
        pluginClass: OuisyncPlugin
      ios:
        pluginClass: OuisyncPlugin
      windows:
        pluginClass: OuisyncPlugin
      linux:
        pluginClass: OuisyncPlugin

